@tool
## As the child of an OpenAction, generates a button that navigates to the menu generated by the linked OpenAction.
class_name CopyOpenAction
extends BaseMenuAction

@export var open_action : OpenAction:
	set(op):
		open_action = op
		update_configuration_warnings()


func _get_configuration_warnings() -> PackedStringArray:
	if open_action == null:
		return ["No linked OpenAction to this copy."]
	return []
